theme: cerulean
markdown: redcarpet
pygments: true

recent_limit: 10
paginate: 10
paginate_path: "blog/page:num"

title: Nathan Courtney
production_url : http://www.nathancourtney.me.uk
rss_path : /rss.xml
