theme: spacelab
markdown: redcarpet
pygments: true

recent_limit: 8
paginate: 12
paginate_path: "blog/page:num"

title: Nathan Courtney
production_url : http://www.nathancourtney.me.uk
rss_path : /rss.xml
baseurl: "/"
